version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysqll
    ports:
      - 3306:3306
    networks:
      test:
        ipv4_address: 10.1.0.100
    volumes:
      - ./sql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test2
      MYSQL_ROOT_HOST: '%'
    restart: always
  app:
    depends_on:
      - db
    image: bagabooengin/app:v1
    ports:
      - 8080:8080
    networks:
      test:
        ipv4_address: 10.1.0.101
    restart: always
    links:
      - db:db
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 80:80
    networks:
      test:
        ipv4_address: 10.1.0.102
networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.1.0.0/24
