
USE `test2`;

INSERT INTO `test2`.`places` (`name`, `image`) VALUES ('The Broken Glass with a bits of extra glass', 'store1.png');
INSERT INTO `test2`.`places` (`name`, `image`) VALUES ('The Salty Sailor weathered folks!', 'store1.png');
INSERT INTO `test2`.`places` (`name`, `image`) VALUES ('The Rocinante business only!', 'store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Blue Moon one on the Earth!','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Martian Dream green in a generation or two!','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Nguen bar famous bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Slumber cafe and chillout place.','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Terminus place for everyone','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Emerald dream for druids','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Juju bar and grill paradise (with bugs)','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Cannon fodder bar anyone who needs some war','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Cafe Latter for coffe','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Generic canteen food','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Brand canteen food for generic people','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('McCornlands based food for fast-fooders','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The zombie land food for project zombies','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Stadium Sports Bar & Eatery','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Provincetown House Of Pizza','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Fionn Mac Cool','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Calendars Restaurant & Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Nuthouse Grill','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Eklund Dining Room & Saloon','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Kickapoo Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Capers Cafe Le Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Colonial Pizza','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('White River Fish Market','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('98 Bar B Que','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Luca Steakhouse','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Main Street Eatery & Catering','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Bronco Billys Ranch Grill','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('2021 Restaurant','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Rasika Restaurant','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Rl Restaurant Ralph Lauren','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Puukaow Thai Restaurant','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Alinea Restaurant Llc','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Mai Thai Cuisine','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Soileaus Dinner Club','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Romeo Italian Grill','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Peaks Lodge & Restaurants','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Windjammer Sports Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Faustina','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Big Bruce Bar-B-Que','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Mc Kinley Fine Bakery & Cafe','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Rogers Zoo','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Aqua Terra','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Pappy Pig Roast & Barbeque','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Ka Prow Pan Asian Bistro','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Sutera Restaurant Westwood','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Casey Seafood Grill & Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Lin Garden','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Joey Restaurant','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Aubree Pizza','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Chinatown Restaurant','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('LA Casa Pizzaria','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Pizza Haven','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Kiku Japanese Steakhouse','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Ponderosa Pines','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Germano Trattoria','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Posados','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Long Grove Cafe','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Tura T Kitchen','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Fat Bob Smokehouse','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Venuti','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Pappy Barbeque Inc','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('LAuberge','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Matteo Pizzeria','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Ale House','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Foundry','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Liberty Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Mountain Village Lounge','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Bareback Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Brothers Grimm','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Ben Place','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Oasis Restaurant & Lounge','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Bullwinkle Saloon','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Mike Calder Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Rum Runner Wine & Spirits','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Max On Broadway','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Highlander Inc','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Fusion 5 Sports Bar & Night','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Arthur','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Monterey Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Rockerfellas','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Jody Restaurant & Lounge','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Wallace Enterprises','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Cabana Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Rocket','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Tomo Japanese Sushi Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Bar None','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Scruples Beach Club','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Sparta Club Oasis','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('22 Doors','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Thomas Street Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('C J Pub Inc','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Kenney Madison Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Old New York New York','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Tropical Liqueurs Bar & Grill','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Coaster Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Screwy Louie','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('O Donoghues Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Boo Radley','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Straight Shooter','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Casey Restaurant','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Howling Coyote','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Dream House','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Oxford Saloon & Eatery','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Good Time Charlie Sports Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Surf Shack','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Harry''o Pest Control','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Crosstown Lounge','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Neumann Bar','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('River Edge','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Bentwood Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Cbgb Downstairs Lounge','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Mad Dogs British Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Derrick Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Ant Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Burping Ankheg Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Cage','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Clumsy Chandler Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Bee & Ratcatcher','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Haughty Prelate Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Princess Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Glass Furrier Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Woodcarver Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Oak Ball Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Wooden Artisan','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Crooked Fisherman Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Horrible Werewolf Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Armorer Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The One-eyed Porter & Happy Solar Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Oak Morlock Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Short Pipe Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Dead Harp Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('White Ranger Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Simple Mule Arms','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Masseur Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Lord & The Chapel Arms','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Snooty Pariah','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Dagger Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Den Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Yelling Concubine Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Witch Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Halfling Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Ram Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Boiling Axe','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Alcove & Carriage','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Cleaver Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Saucy Boatman & Greedy Jongleur','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Trapper','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Flail Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Rat & Rakshasa','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Swan Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Pretty Artist & The Vampire Arms','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Messenger Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Turtle','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Slow Baker Arms','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Berserker Arms','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Eager Undertaker & Petty Haberdasher Pub','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Wolverine Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Yelling Farmer Tavern','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Skinny Nomad','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Rush','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Bottel Inn','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('Witty Lantern & Rampant Nomad','store1.png');
INSERT INTO `test2`.`places` (`name`,`image`) VALUES ('The Duke Pub','store1.png');

UPDATE `test2`.`places` SET `image` = 'store1.png' WHERE (`id` = '1');
UPDATE `test2`.`places` SET `image` = 'store1.png' WHERE (`id` = '2');
UPDATE `test2`.`places` SET `image` = 'store1.png' WHERE (`id` = '3');

# ALTER TABLE `test2`.`foods`
#     ADD COLUMN `descriptions` VARCHAR(128) NULL AFTER `image`,
#     ADD COLUMN `price` INT(11) NULL AFTER `descriptions`;

UPDATE `test2`.`foods` SET `descriptions` = 'cheese Mozzarella, tomato' WHERE (`id` = '1');
UPDATE `test2`.`foods` SET `descriptions` = 'tomato, sauce Margherita' WHERE (`id` = '2');
UPDATE `test2`.`foods` SET `price` = '300' WHERE (`id` = '1');
UPDATE `test2`.`foods` SET `price` = '450' WHERE (`id` = '2');
UPDATE `test2`.`foods` SET `price` = '300' WHERE (`id` = '3');
UPDATE `test2`.`foods` SET `price` = '450' WHERE (`id` = '4');
UPDATE `test2`.`foods` SET `price` = '300' WHERE (`id` = '5');
UPDATE `test2`.`foods` SET `price` = '450' WHERE (`id` = '6');
UPDATE `test2`.`foods` SET `price` = '500' WHERE (`id` = '7');
UPDATE `test2`.`foods` SET `price` = '450' WHERE (`id` = '8');
UPDATE `test2`.`foods` SET `price` = '600' WHERE (`id` = '9');
UPDATE `test2`.`foods` SET `price` = '450' WHERE (`id` = '10');

UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '1');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '2');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '3');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '4');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '5');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '6');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '7');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '8');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '9');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '10');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '11');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '12');
UPDATE `test2`.`foods` SET `image` = 'pizza.jpg' WHERE (`id` = '13');


# ALTER TABLE `test2`.`customers`
#     ADD COLUMN `enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `name`,
#     ADD COLUMN `role` VARCHAR(45) NOT NULL DEFAULT 'USER' AFTER `enabled`;